export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export {default as SocialProof} from './SocialProof'
export {default as Problem} from './Problem'
export {default as Features} from './Features'
export {default as HowItWorks} from './HowItWorks'
export {default as Analytics} from './Analytics'
export {default as AIMatching} from './AIMatching'
export {default as Pricing} from './Pricing'
export {default as CTA} from './CTA'
export {default as Footer} from './Footer'