export const BRAND_PROFILE = {
  id: 'brand-001',
  name: 'Gymshark India',
  initial: 'G',
  industry: 'Fitness & Apparel',
  type: 'D2C Brand',
  location: 'Mumbai, Maharashtra',
  shortLocation: 'Mumbai, India',
  memberSince: 'Jan 2025',
  verified: true,
  activeCampaignsCount: 3,

  bio: `Gymshark India is the official Indian arm of the globally renowned fitness apparel brand Gymshark. We craft performance-first activewear designed for real athletes — whether you're crushing a HIIT session or recovering between sets.

We collaborate with creators who are genuine fitness enthusiasts, not just influencers. Our campaigns focus on authentic storytelling — sweat, progress, and real transformation.

If you're building a fitness community or have a dedicated gym/wellness audience, we'd love to work with you.`,

  fields: [
    { icon: 'Briefcase', key: 'Industry', value: 'Fitness & Apparel' },
    { icon: 'Users', key: 'Company', value: '51–200 employees' },
    { icon: 'DollarSign', key: 'Budget', value: '₹50K – 5L', valueColor: '#1a7a45', bold: true },
    { icon: 'Calendar', key: 'Collab type', value: 'Long-term', tag: true, tagColor: 'blue' },
    { icon: 'Clock', key: 'Avg. response', value: '~4 hours', tag: true, tagColor: 'green' },
  ],

  niches: ['Fitness', 'Lifestyle', 'Gym', 'Nutrition', 'Reels', 'YouTube', 'Sports'],

  socials: [
    { platform: 'Instagram', icon: 'Instagram', label: '@gymshark_india', url: '#' },
    { platform: 'YouTube', icon: 'Youtube', label: 'YouTube', url: '#' },
    { platform: 'Website', icon: 'Link', label: 'gymshark.com/in', url: '#' },
  ],

  stats: [
    { label: 'Total Campaigns', value: '18', delta: '↑ 3 this month', deltaType: 'up', icon: 'LogIn', iconBg: '#eef2fd', iconColor: '#1a4fd4' },
    { label: 'Creators Hired', value: '94', delta: '↑ 12 this quarter', deltaType: 'up', icon: 'Users', iconBg: '#edfaf3', iconColor: '#1a7a45' },
    { label: 'Total Reach', value: '8.4M', delta: '↑ 22% vs last qtr', deltaType: 'up', icon: 'Eye', iconBg: '#fdf5e6', iconColor: '#a0620a' },
    { label: 'Avg. Eng. Rate', value: '4.2%', delta: '↑ 0.6% vs avg', deltaType: 'up', icon: 'TrendingUp', iconBg: '#eef2fd', iconColor: '#1a4fd4' },
    { label: 'Total Spent', value: '₹18.4L', delta: 'All time', deltaType: 'na', icon: 'DollarSign', iconBg: '#edfaf3', iconColor: '#1a7a45' },
  ],

  campaigns: [
    {
      id: 'c1',
      name: 'Summer Shred Challenge — UGC Reels',
      icon: '🏋️',
      iconBg: '#edfaf3',
      meta: ['Instagram Reels', 'Fitness · Gym', 'Nano to Macro'],
      status: 'active',
      progressLabel: 'Applications filled',
      progressValue: '18 / 25 slots',
      progressPct: 72,
      progressColor: 'green',
      tags: ['UGC', 'Reels', 'Gifting'],
      budget: '₹80K',
      budgetLabel: 'budget',
    },
    {
      id: 'c2',
      name: 'New Arrival — Lifting Shoes Launch',
      icon: '👟',
      iconBg: '#eef2fd',
      meta: ['YouTube + Instagram', 'Review · Unboxing'],
      status: 'reviewing',
      progressLabel: 'Applications received',
      progressValue: '11 pending review',
      progressPct: 44,
      progressColor: 'blue',
      tags: ['Review', 'YouTube', 'Paid'],
      budget: '₹1.2L',
      budgetLabel: 'budget',
    },
    {
      id: 'c3',
      name: 'Yoga & Wellness Collab — Q2 2025',
      icon: '🧘',
      iconBg: '#f3eeff',
      meta: ['Instagram · Long-form', "Women's Fitness"],
      status: 'draft',
      progressLabel: 'Campaign readiness',
      progressValue: '20% complete',
      progressPct: 20,
      progressColor: 'muted',
      tags: ['Lifestyle', 'Wellness'],
      budget: '₹60K',
      budgetLabel: 'est.',
    },
  ],

  applications: [
    {
      id: 'a1',
      creatorName: 'Rohit Fitness',
      handle: '@rohit.lifts',
      followers: '480K',
      avatarColor: 'linear-gradient(135deg,#d43a2a,#8a1a10)',
      avatarInitial: 'R',
      campaign: 'Summer Shred',
      stats: [
        { key: 'Followers', value: '480K', icon: 'Users' },
        { key: 'Eng. rate', value: '6.2%', icon: 'TrendingUp' },
        { key: 'Platform', value: 'Instagram', icon: 'Instagram' },
        { key: 'Rate/post', value: '₹8K', icon: 'DollarSign' },
      ],
      pitch: "I've been a Gymshark fan for 3 years and my audience trusts my fitness reviews. I can create 3 dedicated reels showing the shred program with your gear — authentic, no fluff.",
    },
    {
      id: 'a2',
      creatorName: 'Priya Wellness',
      handle: '@priyayoga',
      followers: '210K',
      avatarColor: 'linear-gradient(135deg,#6d3fbd,#3d1a6e)',
      avatarInitial: 'P',
      campaign: 'Yoga Collab',
      stats: [
        { key: 'Followers', value: '210K', icon: 'Users' },
        { key: 'Eng. rate', value: '8.4%', icon: 'TrendingUp' },
        { key: 'Platform', value: 'Instagram', icon: 'Instagram' },
        { key: 'Rate/post', value: '₹5K', icon: 'DollarSign' },
      ],
      pitch: 'Yoga and activewear is my core content. My audience is 80% women aged 22-35 — exactly your target. Would love to do a long-term collab for the wellness line.',
    },
  ],

  pastCollabs: [
    {
      id: 'p1',
      creatorName: 'Rohit Fitness',
      handle: '@rohit.lifts · 480K followers',
      campaign: 'Summer Shred Challenge 2024',
      platform: 'Instagram',
      result: '+2.1M reach',
      emoji: '💪',
      bg: 'linear-gradient(135deg,#0f2027,#203a43,#2c5364)',
      avatarBg: 'linear-gradient(135deg,#d43a2a,#8a1a10)',
      avatarInitial: 'R',
      tags: ['Reels', 'Gym', 'Paid'],
    },
    {
      id: 'p2',
      creatorName: 'Priya Wellness',
      handle: '@priyayoga · 210K subs',
      campaign: 'Womens Activewear Q3 2024',
      platform: 'YouTube',
      result: '+890K views',
      emoji: '🧘',
      bg: 'linear-gradient(135deg,#1a0533,#3d1a6e,#6d3fbd)',
      avatarBg: 'linear-gradient(135deg,#1a4fd4,#0f2d80)',
      avatarInitial: 'P',
      tags: ['YouTube', 'Yoga', 'Review'],
    },
    {
      id: 'p3',
      creatorName: 'Aryan Runs',
      handle: '@aryanruns · 320K followers',
      campaign: 'Marathon Season Campaign 2024',
      platform: 'Instagram + YT',
      result: '+1.4M reach',
      emoji: '🏃',
      bg: 'linear-gradient(135deg,#0a2e1a,#1a5c36,#27ae60)',
      avatarBg: 'linear-gradient(135deg,#1a7a45,#0f4d2b)',
      avatarInitial: 'A',
      tags: ['Running', 'UGC', 'Long-term'],
    },
    {
      id: 'p4',
      creatorName: 'Shruti FitLife',
      handle: '@shruti.fit · 95K followers',
      campaign: 'Boxing & HIIT Collection Drop',
      platform: 'Instagram',
      result: '+560K reach',
      emoji: '🥊',
      bg: 'linear-gradient(135deg,#2d1b00,#8a4800,#c96a00)',
      avatarBg: 'linear-gradient(135deg,#a0620a,#6b4006)',
      avatarInitial: 'S',
      tags: ['Nano', 'High ER', 'Gifting'],
    },
  ],

  reviewSummary: {
    average: 4.5,
    total: 38,
    breakdown: [
      { stars: 5, count: 24, pct: 63 },
      { stars: 4, count: 11, pct: 29 },
      { stars: 3, count: 3, pct: 8 },
      { stars: 2, count: 0, pct: 0 },
    ],
  },

  reviews: [
    {
      id: 'r1',
      creatorName: 'Rohit Fitness',
      campaign: 'Summer Shred Challenge 2024',
      avatarBg: 'linear-gradient(135deg,#d43a2a,#8a1a10)',
      avatarInitial: 'R',
      stars: 5,
      text: 'Working with Gymshark India was seamless. The brief was crystal clear, payment was on time, and they gave me full creative freedom. Rare for a brand this size — genuinely recommend.',
      tags: ['Clear Brief', 'Timely Payment', 'Creative Freedom'],
      date: 'March 2025',
    },
    {
      id: 'r2',
      creatorName: 'Priya Wellness',
      campaign: 'Womens Activewear Q3 2024',
      avatarBg: 'linear-gradient(135deg,#6d3fbd,#3d1a6e)',
      avatarInitial: 'P',
      stars: 5,
      text: 'Absolutely loved this collaboration. The product quality speaks for itself and the team was super responsive. Would love to work with Gymshark India again!',
      tags: ['Responsive', 'Great Product'],
      date: 'Oct 2024',
    },
    {
      id: 'r3',
      creatorName: 'Aryan Runs',
      campaign: 'Marathon Season Campaign 2024',
      avatarBg: 'linear-gradient(135deg,#1a7a45,#0f4d2b)',
      avatarInitial: 'A',
      stars: 4,
      text: 'Good experience overall. Slight delay in approvals but the team was understanding. The campaign results were strong and they shared detailed reporting with me.',
      tags: ['Good Reporting', 'Minor Delays'],
      date: 'Dec 2024',
    },
  ],
}

export const STATUS_PILL_STYLES = {
  active: { bg: 'var(--green-bg)', color: 'var(--green)', label: '● Active' },
  reviewing: { bg: 'var(--amber-bg)', color: 'var(--amber)', label: '⧖ Reviewing' },
  draft: { bg: 'var(--surface)', color: 'var(--ink3)', label: 'Draft' },
}
